version: '3.3'
services:
  rabbit01:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    labels:
      NAME: "rabbit01"
    networks:
      rabbitbr_local:
        ipv4_address: 10.25.25.11
networks:
  rabbitbr_local:
    external:
      name: rabbitbr

